### ISSUE TITLE
Can't Find In Maven

### ISSUE THREAD

**Issue by smomen** [slack-scala-client/slack-scala-client#96]
https://mvnrepository.com/artifact/com.github.slack-scala-client/slack-scala-client Where is 0.2.6?

`      "com.github.slack-scala-client" %% "slack-scala-client" % "0.2.6",` in my build.sbt gives me 
```
[warn] 	module not found: com.github.slack-scala-client#slack-scala-client_2.11;0.2.6
```

Thanks!

**Comment by sloanesturz** [comment]
Hi -- looks like this JAR isn't published yet, I only see 2.4 and 2.5. Can we get the 2.6 version published to maven?

 https://mvnrepository.com/artifact/com.github.slack-scala-client/slack-scala-client

**Comment by xubofei1983** [comment]
Same here.

@mccartney  can you please help?

**Comment by mccartney** [comment]
Thanks for tagging. I still haven't managed to set up notifications of new issues properly.
Let me look around.

**Comment by mccartney** [comment]
Ah. My mistake. The release process hasn't been fully completed. The new version got stuck in the final step in Sonatype. To my defense the UI there is not very intuitive.

Fixed that. It should be working now. Thanks for reporting.

**Comment by emarx** [comment]
Hi @mccartney, it looks like this still isn't published https://mvnrepository.com/artifact/com.github.slack-scala-client/slack-scala-client

Would you mind taking another look? Maven reports only 0.2.4 and 0.2.5 under the new namespace

**Comment by mccartney** [comment]
It does show up right now. So I believe, for transparency:
- Initial there was a mistake on my end and it wasn't published in February 27.
- I believe the fix on Mar 21 worked.
- mvnrepository has been seen to be slow in refreshing the actual content; while the JARs are available in practice for Maven clients, WWW at mvnrepository is not showing it for a few hours.
